/* *** THIS FILE IS GENERATED BY A REALLY SMART ROBOT.      ***
   *** IF YOU EDIT THIS FILE, THE ROBOT WILL EAT YOUR CODE, ***
   *** AND REPLACE YOUR CODE WITH HIS, BECAUSE THAT'S HOW   ***
   *** HE ROLLS. YOU HAVE BEEN WARNED.                      ***

   *** Seriously, if you want to make changes to this file, ***
   *** either run the template that created it again,       ***
   *** or change the template code, at the project path     ***
   *** below.                                               ***

   *** DB.Models/Code Templates/TextTemplate.tt     ***
*/
namespace DB.DAL
{
	using InteractivePreGeneratedViews;
	using log4net;
	
	using System.Data.Entity;

	public partial class ContextDb : DbContext
	{
		#region static members

		public static ILog Log { get; set; }

		#endregion

		#region static constructor

		static ContextDb()
		{
			Database.SetInitializer<ContextDb>(null);
			Log = LogManager.GetLogger(typeof(ContextDb));
			using (var ctx = new ContextDb())
			{
				InteractiveViews
					.SetViewCacheFactory(
						ctx,
						new SqlServerViewCacheFactory(ctx.Database.Connection.ConnectionString));
			}
		}

		#endregion

		#region instance properties

		public int MetricId { get; set; }
		public bool SkipLogging { get; set; }

		#endregion

		#region member datasets

		

		#endregion

		#region Entity Framework configuration

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);
		}

		#endregion
	}
}
