/* *** THIS FILE IS GENERATED BY A REALLY SMART ROBOT.      ***
   *** IF YOU EDIT THIS FILE, THE ROBOT WILL EAT YOUR CODE, ***
   *** AND REPLACE YOUR CODE WITH HIS, BECAUSE THAT'S HOW   ***
   *** HE ROLLS. YOU HAVE BEEN WARNED.                      ***

   *** Seriously, if you want to make changes to this file, ***
   *** either run the template that created it again,       ***
   *** or change the template code, at the project path     ***
   *** below.                                               ***

   *** DB.Models/Code Templates/RxSenseDb.tt     ***
*/
namespace DB.DAL
{
	using InteractivePreGeneratedViews;
	using log4net;
	using Models.DB;
	using System.Data.Entity;

	public partial class RxSenseDb : DbContext
	{
		#region static members

		public static ILog Log { get; set; }

		#endregion

		#region static constructor

		static RxSenseDb()
		{
			Database.SetInitializer<RxSenseDb>(null);
			Log = LogManager.GetLogger(typeof(RxSenseDb));
			using (var ctx = new RxSenseDb())
			{
				InteractiveViews
					.SetViewCacheFactory(
						ctx,
						new SqlServerViewCacheFactory(ctx.Database.Connection.ConnectionString));
			}
		}

		#endregion

		#region instance properties

		public int MetricId { get; set; }
		public bool SkipLogging { get; set; }

		#endregion

		#region member datasets

		public DbSet<AspNetRoleClaimsModel> AspNetRoleClaimsModel { get; set; }
		public DbSet<AspNetRolesModel> AspNetRolesModel { get; set; }
		public DbSet<AspNetUserClaimsModel> AspNetUserClaimsModel { get; set; }
		public DbSet<AspNetUserLoginsModel> AspNetUserLoginsModel { get; set; }
		public DbSet<AspNetUserRolesModel> AspNetUserRolesModel { get; set; }
		public DbSet<AspNetUsersModel> AspNetUsersModel { get; set; }
		public DbSet<AspNetUserTokensModel> AspNetUserTokensModel { get; set; }
		public DbSet<ConsultantModel> ConsultantModel { get; set; }
		public DbSet<ExpertiseAreaModel> ExpertiseAreaModel { get; set; }
		public DbSet<GroupMembersModel> GroupMembersModel { get; set; }
		public DbSet<GroupModel> GroupModel { get; set; }
		public DbSet<GroupTypeModel> GroupTypeModel { get; set; }
		public DbSet<UserModel> UserModel { get; set; }
		public DbSet<WorkExpModel> WorkExpModel { get; set; }

		#endregion

		#region Entity Framework configuration

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);
		}

		#endregion
	}
}
